In [3]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
string = "A Titan RTX has 24GB of VRAM"


In [5]:
tokens = tokenizer(string)
tokenizer.decode(tokens)

'model which takes into account the variations of the smallest thickness measurements'

In [7]:
import torch
a = torch.Tensor([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
b = torch.Tensor([-1,-1,-1,-1,-1,1,1])
print(a[:,b==1].shape())

tensor([[6., 7.],
        [6., 7.],
        [6., 7.]])

In [16]:
import torch
a = torch.Tensor([[[1,2,3,4,5,6,7],[2,2,3,4,5,6,7],[3,2,3,4,5,6,7]],[[4,2,3,4,5,6,7],[5,2,3,4,5,6,7],[6,2,3,4,5,6,7]]])
b = torch.Tensor([[-1,1,1],[1,1,-1]])
print(a[b==1,:].view(2,2,-1))

tensor([[[2., 2., 3., 4., 5., 6., 7.],
         [3., 2., 3., 4., 5., 6., 7.]],

        [[4., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.]]])


In [20]:
a = torch.Tensor([[ 1996, 16293],[ 1996,  1000]])
tokenizer.decode([[ 1996, 16293],[ 1996,  1000]])

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [21]:
list(range(1,4))

[1, 2, 3]

In [1]:
"[MASK]" in '[MASK] [MASK]'

True

In [4]:
tokenizer.mask_token

'[MASK]'

In [8]:
str2=['abc','bacd','adce','b']

notstop = True
while notstop:
    notstop = False
    for i,s in enumerate(str2):
        if 'a' in s:
            str2.pop(i)
            notstop = True
print(str2)

['b']


In [26]:
from transformers import BertTokenizer, BertModel
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [41]:
model.config.hidden_size

768

In [30]:
inputs = tokenizer("The capital of France is [MASK].", return_tensors="pt")
labels = tokenizer("The capital of France is Paris.", return_tensors="pt")["input_ids"]

outputs = model(**inputs, output_hidden_states=True)
# loss = outputs.loss


In [33]:
outputs.last_hidden_state.shape

torch.Size([1, 9, 768])

In [23]:
tokenizer.decode(logits[:,6,:].argmax())

'p a r i s'

In [19]:
torch.cat(outputs.hidden_states).shape

torch.Size([13, 9, 768])

In [43]:
a = torch.Tensor([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]).long()
b = torch.Tensor([0,0,0,0,1,0,1,1]).bool()
a[:,b]

tensor([[5, 7, 8],
        [5, 7, 8]])

In [26]:
import torch
a = torch.ones(5)
b = torch.ones(6)
torch.cat([a,a,a,a])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])

In [20]:
for i in range(8):
    a[:,i:i+1,:]+=i*b

In [18]:
a[:,1:2,:].shape

torch.Size([2, 1, 3])

In [21]:
a

tensor([[[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.]],

        [[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.]]])

In [ ]:
import numpy as np

In [1]:
a=np.load('src_semeval/pointer_net/label.npy')
a=a.tolist()

NameError: name 'np' is not defined